#pragma once
#include "types.h"

// based on the boost implementation of static asserts
template <bool x> struct StaticAssertFailure;
template <> struct StaticAssertFailure <true> { enum { a = 1 }; };
template <int x> struct static_assert_test {};

#define STATIC_ASSERT(a)	typedef static_assert_test <sizeof(StaticAssertFailure<(bool)(a)>)> static_assert_typedef_ ## __COUNTER__

struct Vector
{
	float x, y, z;
};

struct QAngle
{
	float x, y, z;
};

class CGlobalVarsBase {
public:
	float realtime;
	int framecount;
	float absoluteframetime;
	float curtime;
	float frametime;
	int maxClients;
	int tickcount;
	float tick_interval;
	void* saveData;
};

class CGlobalVars : public CGlobalVarsBase
{
public:
	const char* mapname;
	int mapversion;
	const char* startspot;
	bool deathmatch;
	bool coop;
	bool teamplay;
	int cdAudioTrack;
	int maxEntities;

};
class CBaseCombatWeapon {
public:
	CBaseCombatWeapon();
	~CBaseCombatWeapon();
	virtual void Unk01();
	virtual void Unk02();
	virtual void Unk03();
	virtual void Unk04();
	virtual void Unk05();
	virtual void Unk06();
	virtual void Unk07();
	virtual void Unk08();
	virtual void Unk09();
	virtual void Unk10();
	virtual void Unk11();
	virtual void Unk12();
	virtual void Unk13();
	virtual void Unk14();
	virtual void Unk15();
	virtual void Unk16();
	virtual void Unk17();
	virtual void Unk18();
	virtual void Unk19();
	virtual void Unk20();
	virtual void Unk21();
	virtual void Unk22();
	virtual void Unk23();
	virtual void Unk24();
	virtual void Unk25();
	virtual void Unk26();
	virtual void Unk27();
	virtual void Unk28();
	virtual void Unk29();
	virtual void Unk30();
	virtual void Unk31();
	virtual void Unk32();
	virtual void Unk33();
	virtual void Unk34();
	virtual void Unk35();
	virtual void Unk36();
	virtual void Unk37();
	virtual void Unk38();
	virtual void Unk39();
	virtual void Unk40();
	virtual void Unk41();
	virtual void Unk42();
	virtual void Unk43();
	virtual void Unk44();
	virtual void Unk45();
	virtual void Unk46();
	virtual void Unk47();
	virtual void Unk48();
	virtual void Unk49();
	virtual void Unk50();
	virtual void Unk51();
	virtual void Unk52();
	virtual void Unk53();
	virtual void Unk54();
	virtual void Unk55();
	virtual void Unk56();
	virtual void Unk57();
	virtual void Unk58();
	virtual void Unk59();
	virtual void Unk60();
	virtual void Unk61();
	virtual void Unk62();
	virtual void Unk63();
	virtual void Unk64();
	virtual void Unk65();
	virtual void Unk66();
	virtual void Unk67();
	virtual void Unk68();
	virtual void Unk69();
	virtual void Unk70();
	virtual void Unk71();
	virtual void Unk72();
	virtual void Unk73();
	virtual void Unk74();
	virtual void Unk75();
	virtual void Unk76();
	virtual void Unk77();
	virtual void Unk78();
	virtual void Unk79();
	virtual void Unk80();
	virtual void Unk81();
	virtual void Unk82();
	virtual void Unk83();
	virtual void Unk84();
	virtual void Unk85();
	virtual void Unk86();
	virtual void Unk87();
	virtual void Unk88();
	virtual void Unk89();
	virtual void Unk90();
	virtual void Unk91();
	virtual void Unk92();
	virtual void Unk93();
	virtual void Unk94();
	virtual void Unk95();
	virtual void Unk96();
	virtual void Unk97();
	virtual void Unk98();
	virtual void Unk99();
	virtual void Unk100();
	virtual void Unk101();
	virtual void Unk102();
	virtual void Unk103();
	virtual void Unk104();
	virtual void Unk105();
	virtual void Unk106();
	virtual void Unk107();
	virtual void Unk108();
	virtual void Unk109();
	virtual void Unk110();
	virtual void Unk111();
	virtual void Unk112();
	virtual void Unk113();
	virtual void Unk114();
	virtual void Unk115();
	virtual void Unk116();
	virtual void Unk117();
	virtual void Unk118();
	virtual void Unk119();
	virtual void Unk120();
	virtual void Unk121();
	virtual void Unk122();
	virtual void Unk123();
	virtual void Unk124();
	virtual void Unk125();
	virtual void Unk126();
	virtual void Unk127();
	virtual void Unk128();
	virtual void Unk129();
	virtual void Unk130();
	virtual void Unk131();
	virtual void Unk132();
	virtual void Unk133();
	virtual void Unk134();
	virtual void Unk135();
	virtual void Unk136();
	virtual void Unk137();
	virtual void Unk138();
	virtual void Unk139();
	virtual void Unk140();
	virtual void Unk141();
	virtual void Unk142();
	virtual void Unk143();
	virtual void Unk144();
	virtual void Unk145();
	virtual void Unk146();
	virtual void Unk147();
	virtual void Unk148();
	virtual void Unk149();
	virtual void Unk150();
	virtual void Unk151();
	virtual void Unk152();
	virtual void Unk153();
	virtual void Unk154();
	virtual void Unk155();
	virtual void Unk156();
	virtual void Unk157();
	virtual void Unk158();
	virtual void Unk159();
	virtual void Unk160();
	virtual void Unk161();
	virtual void Unk162();
	virtual void Unk163();
	virtual void Unk164();
	virtual void Unk165();
	virtual void Unk166();
	virtual void Unk167();
	virtual void Unk168();
	virtual void Unk169();
	virtual void Unk170();
	virtual void Unk171();
	virtual void Unk172();
	virtual void Unk173();
	virtual void Unk174();
	virtual void Unk175();
	virtual void Unk176();
	virtual void Unk177();
	virtual void Unk178();
	virtual void Unk179();
	virtual void Unk180();
	virtual void Unk181();
	virtual void Unk182();
	virtual void Unk183();
	virtual void Unk184();
	virtual void Unk185();
	virtual void Unk186();
	virtual void Unk187();
	virtual void Unk188();
	virtual void Unk189();
	virtual void Unk190();
	virtual void Unk191();
	virtual void Unk192();
	virtual void Unk193();
	virtual void Unk194();
	virtual void Unk195();
	virtual void Unk196();
	virtual void Unk197();
	virtual void Unk198();
	virtual void Unk199();
	virtual void Unk200();
	virtual void Unk201();
	virtual void Unk202();
	virtual void Unk203();
	virtual void Unk204();
	virtual void Unk205();
	virtual void Unk206();
	virtual void Unk207();
	virtual void Unk208();
	virtual void Unk209();
	virtual void Unk210();
	virtual void Unk211();
	virtual void Unk212();
	virtual void Unk213();
	virtual void Unk214();
	virtual void Unk215();
	virtual void Unk216();
	virtual void Unk217();
	virtual void Unk218();
	virtual void Unk219();
	virtual void Unk220();
	virtual void Unk221();
	virtual void Unk222();
	virtual void Unk223();
	virtual void Unk224();
	virtual void Unk225();
	virtual void Unk226();
	virtual void Unk227();
	virtual void Unk228();
	virtual void Unk229();
	virtual void Unk230();
	virtual void Unk231();
	virtual void Unk232();
	virtual void Unk233();
	virtual void Unk234();
	virtual void Unk235();
	virtual void Unk236();
	virtual void Unk237();
	virtual void Unk238();
	virtual void Unk239();
	virtual void Unk240();
	virtual void Unk241();
	virtual void Unk242();
	virtual void Unk243();
	virtual void Unk244();
	virtual void Unk245();
	virtual void Unk246();
	virtual void Unk247();
	virtual void Unk248();
	virtual void Unk249();
	virtual void Unk250();
	virtual void Unk251();
	virtual void Unk252();
	virtual void Unk253();
	virtual void Unk254();
	virtual void Unk255();
	virtual void Unk256();
	virtual void Unk257();
	virtual void Unk258();
	virtual void Unk259();
	virtual void Unk260();
	virtual void Unk261();
	virtual void Unk262();
	virtual void Unk263();
	virtual void Unk264();
	virtual void Unk265();
	virtual void Unk266();
	virtual void Unk267();
	virtual void Unk268();
	virtual void Unk269();
	virtual void Unk270();
	virtual void Unk271();
	virtual void Unk272();
	virtual void Unk273();
	virtual void Unk274();
	virtual void Unk275();
	virtual void Unk276();
	virtual void Unk277();
	virtual void Unk278();
	virtual void Unk279();
	virtual void Unk280();
	virtual void Unk281();
	virtual void Unk282();
	virtual void Unk283();
	virtual void Unk284();
	virtual void Unk285();
	virtual void Unk286();
	virtual void Unk287();
	virtual void Unk288();
	virtual void Unk289();
	virtual void Unk290();
	virtual void Unk291();
	virtual void Unk292();
	virtual void Unk293();
	virtual void Unk294();
	virtual void Unk295();
	virtual void Unk296();
	virtual void Unk297();
	virtual void Unk298();
	virtual void Unk299();
	virtual void Unk300();
	virtual void Unk301();
	virtual void Unk302();
	virtual void Unk303();
	virtual void Unk304();
	virtual void Unk305();
	virtual void Unk306();
	virtual void Unk307();
	virtual void Unk308();
	virtual void Unk309();
	virtual void Unk310();
	virtual void Unk311();
	virtual void Unk312();
	virtual void Unk313();
	virtual void Unk314();
	virtual void Unk315();
	virtual void Unk316();
	virtual void Unk317();
	virtual void Unk318();
	virtual void Unk319();
	virtual void Unk320();
	virtual void Unk321();
	virtual void Unk322();
	virtual void Unk323();
	virtual void Unk324();
	virtual void Unk325();
	virtual void Unk326();
	virtual void Unk327();
	virtual void Unk328();
	virtual void Unk329();
	virtual void Unk330();
	virtual void Unk331();
	virtual void Unk332();
	virtual void Unk333();
	virtual void Unk334();
	virtual void Unk335();
	virtual void Unk336();
	virtual void Unk337();
	virtual void Unk338();
	virtual void Unk339();
	virtual void Unk340();
	virtual void Unk341();
	virtual void Unk342();
	virtual void Unk343();
	virtual void Unk344();
	virtual void Unk345();
	virtual void Unk346();
	virtual void Unk347();
	virtual void Unk348();
	virtual void Unk349();
	virtual void Unk350();
	virtual void Unk351();
	virtual void Unk352();
	virtual void Unk353();
	virtual void Unk354();
	virtual void Unk355();
	virtual void Unk356();
	virtual void Unk357();
	virtual void Unk358();
	virtual void Unk359();
	virtual void Unk360();
	virtual void Unk361();
	virtual void Unk362();
	virtual void Unk363();
	virtual void Unk364();
	virtual void Unk365();
	virtual void Unk366();
	virtual void Unk367();
	virtual void Unk368();
	virtual void Unk369();
	virtual void Unk370();
	virtual void Unk371();
	virtual bool IsStackable();

	UInt8 gap00[0x8CA];
	int stackCount;
};

class CBaseEntity
{
public:
	CBaseEntity();
	~CBaseEntity();
	virtual int sub_74D7(int a1);
	virtual int sub_6393();
	virtual int sub_A71D();
	virtual int sub_1570D();
	virtual void* unk();
	virtual int sub_149C5(char a1);
	virtual int SetCheckUntouch(char a1);
	virtual int SetSentLastFrame(char a1);
	virtual int GetModelIndex();
	virtual int GetModelName(int a1);
	virtual int SetModelIndex(int a1);
	virtual int DebugSetEntityName(int a1);
	virtual int DebugGetEntityName();
	virtual int DebugSetClassName(int a1);
	virtual int sub_159D8();
	virtual int SetAttackExtents(int a1);
	virtual int sub_7162(int a1);
	virtual int sub_1171B(int a1, int a2);
	virtual int TraceMessage(int a1, int a2);
	virtual int sub_D34B(int a1);
	virtual int TraceMessageBare(int a1);
	virtual int j_nullsub_109(int a1);
	virtual int j_nullsub_110(int a1);
	virtual int j_nullsub_111(int a1);
	virtual int j_nullsub_112(int a1);
	virtual int j_nullsub_113(int a1);
	virtual int j_nullsub_114(int a1);
	virtual int j_nullsub_115(int a1);
	virtual int sub_73CE();
	virtual int sub_11AE();
	virtual int sub_1325A();
	virtual int Dump(float a1);
	virtual int sub_20CC(int a1);
	virtual int unk2();
	virtual int GetHighlightMaterial(int a1);
	virtual int sub_2338(int a1);
	virtual int sub_CA3B();
	virtual int sub_9827();
	virtual int unk3(int a1);
	virtual int sub_15262(int a2);
	virtual int j_nullsub_116(int a1);
	virtual int j_nullsub_117(int a1);
	virtual int sub_10E60(int a2);
	virtual int j_nullsub_118(int a1);
	virtual int sub_FEF7(int a1);
	virtual int PassesFindEntityFOVTrace(int a1, float a2, float a3, float a4, float a5, float a6, float a7, int a8);
	virtual int j_nullsub_119();
	virtual int j_nullsub_120();
	virtual int sub_2464();
	virtual int sub_79AA();
	virtual int GetCameraViewpointPosition(int a1);
	virtual int GetCameraTargetPosition(int a1, int a2);
	virtual int GetCameraFadeInTime();
	virtual int GetCameraFadeOutTime();
	virtual int sub_F6CD(int a1);
	virtual int j_nullsub_121(int a1, int a2, int a3, int a4, int a5, int a6, int a7);
	virtual int j_nullsub_122(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8);
	virtual int j_nullsub_123(int a1, int a2, int a3, int a4, int a5, int a6, int a7);
	virtual int j_nullsub_124(int a1);
	virtual int j_nullsub_125(int a1);
	virtual int j_nullsub_126(int a1);
	virtual int j_nullsub_127(int a1);
	virtual int SetOrigin(int a1);
	virtual int sub_E03E(int a1, int a2, int a3);
	virtual int SetAngles(int a1);
	virtual int sub_A9B1(int a1, int a2, int a3);
	virtual int Hide();
	virtual int Unhide();
	virtual int ShouldIgnoreCollision(int a1);
	virtual int sub_FDB2(int a1);
	virtual char sub_1145();
	virtual int PrecacheSoundTable();
	virtual int sub_12FBC(int a1);
	virtual int CausesImpactDamage(int a1);
	virtual int ReceivesImpactDamage(int a1);
	virtual int TakeDamageFromCollision(int a2, int a3);
	virtual int j_nullsub_128();
	virtual int ScriptHide();
	virtual int ScriptUnhide();
	virtual int sub_13057();
	virtual int sub_8DF5();
	virtual int sub_1293B();
	virtual int sub_A7A9();
	virtual int sub_1410F();
	virtual int sub_D468(int a1);
	virtual int GetEdict();
	virtual int ShouldTransmit(int a1, int a2, int a3, int a4, int a5);
	virtual int SetTransmit(int a1);
	virtual int sub_6889();
	virtual int sub_E11F();
	virtual int IsTransparent();
	virtual int sub_119DC(int a1, int a2);
	virtual int GetSolid();
	virtual int SetMoveType(int a1, int a2);
	virtual int GetMoveType();
	virtual int GetMoveCollide();
	virtual int GetAimEntEdict();
	virtual int GetOwnerEntity();
	virtual int CalcAbsolutePosition();
	virtual char TestCollision(int a2, int a3, int a4);
	virtual int TestHitboxes(int a1, int a2, int a3);
	virtual int j_nullsub_129(int a1, int a2);
	virtual int sub_FACE(int a1, int a2, int a3, int a4, int a5);
	virtual int Spawn();
	virtual int Precache();
	virtual int SetModel(int a2);
	virtual int PostConstructor(int a1);
	virtual int ParseMapData(int a1);
	virtual int sub_A5E7(int a1, int a2, int a3, int a4);
	virtual int sub_73E7(int a1, float a2);
	virtual int sub_7428(char* String1, char* String);
	virtual int MemberSync();
	virtual int j_nullsub_132(int a1, int a2);
	virtual int Activate();
	virtual int PostClientMessagesSent();
	virtual int j_nullsub_133(int a1);
	virtual int sub_10B09();
	virtual int sub_6703();
	virtual int AcceptInput(char* String2, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9);
	virtual int Kill();
	virtual int GetInputDispatchEffectPosition(int a1, int a2, int a3);
	virtual int ReadKeyField(char* String2, int a2);
	virtual int SetClassname(char* Source);
	virtual int DrawDebugGeometryOverlays();
	virtual int DrawDebugTextOverlays();
	virtual int DrawMuzzleOverlay();
	virtual int Save(int a1);
	virtual int Restore(int a1);
	virtual int ShouldSavePhysics();
	virtual int OnSave();
	virtual int sub_BFCD(int a1);
	virtual void* duplicate_33_1();
	virtual int j_nullsub_134();
	virtual int sub_13912();
	virtual int Think();
	virtual int sub_443A(float a1);
	virtual int sub_15C26();
	virtual void duplicate_4_1();
	virtual int sub_7388();
	virtual int j_nullsub_135(int a1);
	virtual int PassesDamageFilter(int a1);
	virtual int TraceAttack(int a1, float a2, int a3);
	virtual int OnTakeDamage(int a1);
	virtual int TakeHealth(float a1, int a2);
	virtual int Event_Killed(int a2);
	virtual int sub_32D8();
	virtual int sub_7987(int a1, int a2, int a3);
	virtual int sub_74FF(int a1);
	virtual int j_nullsub_136(int a1, int a2);
	virtual int j_nullsub_137(int a1, int a2);
	virtual int sub_FC8B(int a1);
	virtual int sub_14803(int a1);
	virtual int sub_29CD();
	virtual int sub_7A04();
	virtual int sub_B9E2(int a1, int a2);
	virtual int DecalTrace(int a1, int a2, char a3, int a4, int a5, int a6, char a7);
	virtual int j_nullsub_138(int a1);
	virtual int sub_9318(int a1);
	virtual int sub_5330();
	virtual int sub_119A5();
	virtual int HasTarget(char* String1);
	virtual int HasLinkedDoor(char* String1);
	virtual bool IsPlayer();
	virtual int IsViewable();
	virtual int sub_D495();
	virtual int sub_12E90(int a1);
	virtual int sub_128D7(int a1);
	virtual int sub_3760();
	virtual int sub_B7A8();
	virtual int j_nullsub_139(int a1);
	virtual int j_nullsub_140(int a1);
	virtual int SetMovedir();
	virtual int GetNextTarget();
	virtual int Use(int a1, int a2, int a3, int a4);
	virtual int StartTouch(int a1);
	virtual int Touch(int a1);
	virtual int EndTouch(int a2);
	virtual int j_nullsub_141(int a1);
	virtual int Blocked(int a1);
	virtual int j_nullsub_142();
	virtual int UpdateOnRemove();
	virtual int Teleport(int a1, int a2, int a3);
	virtual int j_nullsub_143(int a1, int a2, int a3, int a4);
	virtual int j_nullsub_144(int a1, int a2, int a3);
	virtual int sub_CB1C(int a1, int a2, int a3);
	virtual int sub_12FD5(int a1);
	virtual int sub_475F();
	virtual int sub_5187();
	virtual int sub_9C0F();
	virtual int GetDamageType();
	virtual int sub_7B44();
	virtual int j_nullsub_145(int a1);
	virtual int sub_7A0E(int a1);
	virtual int sub_7941(int a1);
	virtual int sub_114A();
	virtual int sub_11379();
	virtual int sub_A961(int a1);
	virtual int BodyTarget(int a1, int a2, int a3, int a4);
	virtual int sub_EC41();
	virtual int GetVelocity(int a1, int a2);
	virtual int Illumination();
	virtual char FVisible(int a2, int a3, void* a4, int a5);
	virtual int SetOwnerEntity(int a1);
	virtual int GetAttackDamageScale();
	virtual int GetReceivedDamageScale();
	virtual int sub_E34A();
	virtual int sub_F81C(int a1, int a2, int a3, int a4, int a5);
	virtual int IsCurrentlyTouching();
	virtual int SetGroundEntity(int a1);
	virtual int GetGroundEntity();
	virtual int sub_DED1(int a1);
	virtual int GetSolidFlags();
	virtual int SetModelName(int a1);
	virtual int sub_9796(int a1);
	virtual int GetSize();
	virtual int sub_13967();
	virtual int SetAbsOrigin(int a1);
	virtual int GetAbsOrigin();
	virtual int SetAbsAngles(int a1);
	virtual int GetAbsAngles();
	virtual int GetOrigin();
	virtual int GetAngles();
	virtual int GetSoundEmissionOrigin(int a1);
	virtual int sub_10F78();
	virtual int sub_722A(int a1);
	virtual int sub_133F4();
	virtual int sub_CFA9(int a1);
	virtual int VPhysicsTakeDamage(int a1);
	virtual int VPhysicsShadowCollision(int a1, int a2);
	virtual int j_nullsub_146(int a1);
	virtual int VPhysicsCollision(int a2, int a3);
	virtual int VPhysicsFriction(int a2, float a3, int a4, int a5);
	virtual int UpdatePhysicsShadowToCurrentPosition(int a1);
	virtual int VPhysicsGetObjectList(int a1, int a2);
	virtual int PhysicsPushEntity(int a1, int a2);
	virtual int j_nullsub_147(int a1);
	virtual int j_nullsub_148(int a1, int a2);
	virtual int PhysicsSolidMaskForEntity();
	virtual int PerformCustomPhysics(int a1, int a2, int a3, int a4);
	virtual char field_3BC(int a1);
	virtual int field_3C0(int a2);

	UInt8 gap_4[160];
	UInt32 field_A4;
	UInt8 gap_A8[108];
	void(__thiscall* m_pfnMoveDone)(CBaseEntity*);
	UInt8 gap_118[4];
	UInt32 field_11C;
	UInt8 gap_120[68];
	float m_flSpeed;
	UInt8 gap_168[20];
	float fMoveDoneTime;
	UInt8 gap_180[16];
	Vector m_vecMoveDir;
	UInt8 gap_19C[80];
	void(__thiscall* m_pfnTouch)(CBaseEntity*, CBaseEntity*);
	UInt8 gap_1F0[20];
	UInt32 m_spawnFlags;
	UInt8 gap_208[36];
	int m_nSimulationTick;
	UInt8 gap_230[56];
	int m_iEFlags;
	const char* m_iName;
	float field_270;
	UInt8 gap_274[32];
	float field_294;
	UInt8 gap_298[292];
	Vector m_vecAbsVelocity;
	Vector m_vecAngVelocity;
	UInt8 gap3D4[40];
	float field_3FC;
	UInt8 gap_400[80];
};
STATIC_ASSERT(sizeof(CBaseEntity) == 0x450);


class CBaseToggle: public CBaseEntity
{
public:
	CBaseToggle();
	~CBaseToggle();
	UInt8 gap_450[168];
	UInt32 m_toggle_state;
	float m_flMoveDistance;
	float m_flWait;
	float m_flLip;
	Vector m_vecPosition1;
	Vector m_vecPosition2;
	UInt8 gap_520[28];
	UInt32 m_hActivator;
	Vector m_vecFinalDest;
	QAngle m_vecFinalAngle;
	int m_movementType;
};
STATIC_ASSERT(sizeof(CBaseToggle) == 0x55C);

